Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -98,36 +98,42 @@ jobs:
       GOPATH: ${{ github.workspace }}
       GO111MODULE: auto
       CI_TEST_FLAGS: -race -coverprofile=coverage.txt -covermode=atomic
-#    defaults:
- #     run:
-  #      working-directory: ${{ env.GOPATH }}/src/github.com/fluid-cloudnative/fluid      
+    defaults:
+      run:
+        working-directory: ${{ env.GOPATH }}/src/github.com/fluid-cloudnative/fluid      
     runs-on: self-hosted
     steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-      #with:
-       # path: ${{ env.GOPATH }}/src/github.com/fluid-cloudnative/fluid
-      
-    - name: build
-      run: |
-            sudo apt-get install -y curl golang-go make git && \
-            export GOPATH=/root/go && \
-            export PATH=$PATH:$GOROOT/bin:$GOPATH/bin && \
-            go env && \
-            pwd && \
-            #sudo mkdir -p $GOPATH/src/github.com/fluid-cloudnative/ && \
-            #sudo cd $GOPATH/src/github.com/fluid-cloudnative && \
-            #sudo git clone https://github.com/fluid-cloudnative/fluid.git && \
-            #sudo cd fluid && \
-            arch=$(go env GOARCH) && \
-            os=$(go env GOOS) && \
-            cd /home/hirni/go/actions-runner/_work/fluid/fluid && \
-            #sudo curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_${os}_${arch}.tar.gz | tar -xz -C /tmp/ && \
-            #sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder && \
-            export PATH=$PATH:/usr/local/kubebuilder/bin && \
-            make build && \
-            export KUBE_CONFIG_PATH=~/.kube/config && \
-            make test && \
-            echo $(git status --porcelain | grep generated) && \
-            if [ -z "$(git status --porcelain | grep generated)" ]; then echo "openapi validation passed."; else echo "openapi validation failed. Please use make build to update openapi"; exit 1; fi && \
-            bash <(curl -s https://codecov.io/bash)
+      - name: Set up Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.17
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          path: ${{ env.GOPATH }}/src/github.com/fluid-cloudnative/fluid
+
+      - name: build
+        run: |
+              sudo apt-get install -y curl golang-go make git && \
+              export GOPATH=/root/go && \
+              export PATH=$PATH:$GOROOT/bin:$GOPATH/bin && \
+              go env && \
+              pwd && \
+              sudo su && \
+              mkdir -p $GOPATH/src/github.com/fluid-cloudnative/ && \
+              cd $GOPATH/src/github.com/fluid-cloudnative && \
+              git clone https://github.com/fluid-cloudnative/fluid.git && \
+              cd fluid && \
+              arch=$(go env GOARCH) && \
+              os=$(go env GOOS) && \
+              #cd /home/hirni/go/actions-runner/_work/fluid/fluid && \
+              #sudo curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_${os}_${arch}.tar.gz | tar -xz -C /tmp/ && \
+              #sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder && \
+              export PATH=$PATH:/usr/local/kubebuilder/bin && \
+              make build && \
+              export KUBE_CONFIG_PATH=~/.kube/config && \
+              make test && \
+              echo $(git status --porcelain | grep generated) && \
+              if [ -z "$(git status --porcelain | grep generated)" ]; then echo "openapi validation passed."; else echo "openapi validation failed. Please use make build to update openapi"; exit 1; fi && \
+              bash <(curl -s https://codecov.io/bash)
