Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -109,12 +109,20 @@ jobs:
               export GOPATH=/home/hirni/actions-runner/_work/go && \
               export PATH=$PATH:$GOROOT/bin:$GOPATH/bin && \
               sudo chmod 777 -R /home/hirni/actions-runner/_work/go/src/github.com/fluid-cloudnative/fluid/ && \
-              #sudo chmod 777 /home/hirni/actions-runner/_work/go/src/github.com/fluid-cloudnative/fluid/bin/ && \
-              #sudo chmod 777 /home/hirni/actions-runner/_work/go/src/github.com/fluid-cloudnative/fluid/coverage.txt && \
               cd /home/hirni/actions-runner/_work/go/src/github.com/fluid-cloudnative/fluid && \
               git config --global --add safe.directory /home/hirni/actions-runner/_work/go/src/github.com/fluid-cloudnative/fluid && \
               arch=$(go env GOARCH) && \
               os=$(go env GOOS) && \
+              curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0 && \
+              curl -L https://get.helm.sh/helm-v3.7.2-${os}-${arch}.tar.gz | tar -xz -C /home/hirni/actions-runner/tmp && \
+              chmod u+x /home/hirni/actions-runner/tmp/${os}-${arch}/helm && sudo mv /home/hirni/actions-runner/tmp/${os}-${arch}/helm /usr/local/bin/helm && \
+              make update-crd && \
+              git status --porcelain && \
+              if [ -z "`git status --porcelain`" ]; then echo "CRD validation passed."; else echo "CRD validation failed. Please use 'make update-crd' to keep CRDs latest"; exit 1; fi && \
+              golangci-lint run --timeout=10m && \
+              test -z "$(go fmt ./... 2>/dev/null | tee /dev/stderr)" || (echo "please format Go code with 'gofmt'") && \
+              go vet ./... && \
+              find ./charts | grep Chart.yaml | xargs dirname | xargs helm lint && \
               #sudo curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_${os}_${arch}.tar.gz | tar -xz -C /tmp/ && \
               #sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder && \
               #export PATH=$PATH:/usr/local/kubebuilder/bin && \
